site_name: Qualitative Research and Computers

nav:
  - Home: index.md
  - Open coding:
    - Introduction: open-coding/index.md
    - Atlas.TI: open-coding/atlasti.md
    - Atlas.TI 8 (old version): open-coding/atlasti_8.md
  - Closed coding:
    - Introduction: closed-coding/index.md
    - DiscoverText: closed-coding/discovertext.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png

extra_css:
  - stylesheets/extra.css

plugins: []
