site_name: Qualitative Research and Computers

nav:
  - Home: index.md
  - Open coding:
    - Introduction: open-coding/index.md
    - ATLAS.ti: open-coding/atlasti.md
    - Old materials:
      - ATLAS.ti 22 (desktop only): open-coding/atlasti_desktop.md
      - ATLAS.ti 9 (old version): open-coding/atlasti_9_desktop.md
      - ATLAS.ti 8 (old version): open-coding/atlasti_8.md
  - Closed coding:
    - Introduction: closed-coding/index.md
    - Label Studio: closed-coding/labelstudio.md
    - Old materials:
      - Spreadsheet: closed-coding/spreadsheet.md
      - DiscoverText: closed-coding/discovertext.md
  - Beyond text:
    - Introduction: beyond-text/index.md
    - ATLAS.ti for images: beyond-text/atlasti.md
    - Image recongition services: beyond-text/imagerecognition.md
  - Data science:
    - Introduction: data-science/index.md
    - RapidMiner: data-science/rapidminer.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png

extra_css:
  - stylesheets/extra.css

plugins: []

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
